version: "3"

services:
  express:
    build:
      context: .
      dockerfile: ./docker/express/Dockerfile
    image: express
    container_name: express
    environment:
      - DB_HOST=host.docker.internal
      - DB_DATABASE=appdb
      - DB_USER=appdb
      - DB_PASSWORD=appdb
      - HISTSIZE=10000
      - HISTFILE=/usr/src/app/.bash_history
    ports:
      - "3000:3000"
    volumes:
      - "./src:/usr/src/src"
    command: bash -c "npm run dev"

  admin:
    image: dpage/pgadmin4
    user: 5050:5050
    container_name: admin
    ports:
      - 4000:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pg.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    restart: always

  nginx:
    build:
      context: ./docker/nginx
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    environment:
      - WEB_HOST=host.docker.internal
    command: /bin/sh -c "envsubst '$$WEB_HOST' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

volumes:
  pgadmin: